### ISSUE TITLE
正文字号与行距与模版不一致

### ISSUE THREAD

**Issue by sinceseto** [h-hg/latex-scut-bachelor-thesis#1]
感谢你写的模版！非常有用！
我发现一个小问题，使用windows平台进行编译，发现正文部分字体与行距都与模版的小四号1.5倍行距不一致，![image](https://user-images.githubusercontent.com/44320134/168766533-26ff4bb1-0e88-45ad-894d-72f3ca5ba1d8.png)
模版
![image](https://user-images.githubusercontent.com/44320134/168767618-e5a217db-97bc-4331-9961-708362d5cb3c.png)
字看起来比较挤，我不是特别会latex，尝试在main.tex添加
```
\begin{spacing}{1.5}
\zihao{-4}
% 被包含章节
\end{spacing}
```
之后感觉会正常一些

![image](https://user-images.githubusercontent.com/44320134/168766295-ccfcd676-8012-48e6-aeff-af1156467989.png)

**Comment by h-hg** [comment]
确实有这个问题，模板是有用 `\onehalfspacing` 的，但貌似没效果，有待后面有空了再查阅修正，Latex 的行距概念跟 Word 貌似不太一样。
你能自己解决问题，真的太好！
感谢使用，预祝毕业顺利！
